name: MCTycoon
version: 1.0.0
main: dev.vacariu.MCTycoon.TycoonMain
description: Stealgens plugin
author: andreivacariu
website: https://vacariu.dev
api-version: '1.16'
depend: [RedLib, Vault]
commands:
  tycoon:
  shop:
